CREATE DATABASE TAYNGUYENFOOD
GO

/*Create DISCOUNT*/
CREATE TABLE [dbo].[DISCOUNT] (
    [DiscountID]      VARCHAR(10) NOT NULL,
    [DiscountPercent] TINYINT NOT NULL,
    [DiscountLimit]   INT NOT NULL,
    CONSTRAINT [PK_DISCOUNT] PRIMARY KEY CLUSTERED ([DiscountID] ASC)
);

/*Create DEPARTMENT*/
CREATE TABLE [dbo].[DEPARTMENT] (
    [DepartmentID]   CHAR (2)      NOT NULL,
    [DepartmentName] NVARCHAR (20) NOT NULL,
    [ManagerID]      VARCHAR (10)  NOT NULL,
    CONSTRAINT [PK_DEPARTMENT] PRIMARY KEY CLUSTERED ([DepartmentID] ASC)
);
/*Create EMPLOYEE*/
CREATE TABLE [dbo].[EMPLOYEE] (
    [EmployeeID]       TINYINT       NOT NULL,
    [EmployeeName]     NVARCHAR (50) NOT NULL,
    [DepartmentID]       CHAR (2)      NOT NULL,
    [Email]            VARCHAR (50)  NOT NULL,
    [Phone]            INT           NOT NULL,
    [EmpAddressNumber] NVARCHAR (50) NOT NULL,
    [EmpWard]          NVARCHAR (30) NOT NULL,
    [EmpDistrict]      NVARCHAR (20) NOT NULL,
    [EmpProvince]      NVARCHAR (50) NOT NULL,
    [EmployeeType]     BIT           NOT NULL,
    CONSTRAINT [PK_EMPLOYEE] PRIMARY KEY CLUSTERED ([EmployeeID] ASC)
);
ALTER TABLE EMPLOYEE
   ADD CONSTRAINT FK_EMPLOYEE_DEPARTMENT FOREIGN KEY (DepartmentID)
      REFERENCES DEPARTMENT(DepartmentID) 

/*Create SHIPPING UNIT*/
CREATE TABLE [dbo].[SHIPPING_UNIT] (
    [ShippingUnitID] VARCHAR (5)    NOT NULL,
    [Name]           NVARCHAR (30)  NOT NULL,
    [Address]        NVARCHAR (200) NOT NULL,
    [Email]          VARCHAR(50)           NOT NULL,
    [Phone]          INT            NOT NULL
    CONSTRAINT [PK_SHIPPING_UNIT] PRIMARY KEY CLUSTERED ([ShippingUnitID] ASC)
);
/*Create CUSTOMER*/
CREATE TABLE [dbo].[CUSTOMER] (
    [CustomerID] INT           NOT NULL,
    [CustomerName] NVARCHAR (50) NOT NULL,
    [Phone] INT           NOT NULL,
    [Email] VARCHAR(50)           NOT NULL,
    [LoginType] CHAR(2)           NOT NULL,
    CONSTRAINT [PK_CUSTOMER] PRIMARY KEY CLUSTERED ([CustomerID] ASC)
);
/*Create WEBSITE_ACCOUNT*/
 CREATE TABLE [dbo].[WEBSITE_ACCOUNT] (
    [WACusID]  INT  NOT NULL,
    [Username] NVARCHAR (50) NOT NULL,
    [Password] NVARCHAR (20) NOT NULL,
    CONSTRAINT [PK_WEBSITE_ACCOUNT] PRIMARY KEY CLUSTERED ([WACusID] ASC)
);
ALTER TABLE WEBSITE_ACCOUNT
   ADD CONSTRAINT FK_WEBSITE_ACCOUNT_CUSTOMER FOREIGN KEY (WACusID)
      REFERENCES CUSTOMER(CustomerID);

/*Create FACEBOOK*/
CREATE TABLE [dbo].[FACEBOOK] (
    [FBCusID] INT NOT NULL,
    [FBName]  NVARCHAR (50) NOT NULL,
    [FBLink]  VARCHAR (60)  NOT NULL,
    CONSTRAINT [PK_FACEBOOK] PRIMARY KEY CLUSTERED ([FBCusID] ASC)
);
ALTER TABLE FACEBOOK
   ADD CONSTRAINT FK_FACEBOOK_CUSTOMER FOREIGN KEY (FBCusID)
      REFERENCES CUSTOMER(CustomerID);

/*Create GOOGLE*/
CREATE TABLE [dbo].[GOOGLE] (
    [GGCusID] INT NOT NULL,
    [GGName]  NVARCHAR (50) NOT NULL,
    CONSTRAINT [PK_GOOGLE] PRIMARY KEY CLUSTERED ([GGCusID] ASC)
);
ALTER TABLE GOOGLE
   ADD CONSTRAINT FK_GOOGLE_CUSTOMER FOREIGN KEY (GGCusID)
      REFERENCES CUSTOMER(CustomerID)

/*Create CATEGORY*/
CREATE TABLE [dbo].[CATEGORY] (
    [CategoryID]    VARCHAR (10) NOT NULL,
    [Category Name] NVARCHAR (30)   NOT NULL,
    CONSTRAINT [PK_CATEGORY] PRIMARY KEY CLUSTERED ([CategoryID] ASC)
);
/*Create PRODUCT*/
CREATE TABLE [dbo].[PRODUCT] (
    [ProductID]     VARCHAR (10)  NOT NULL,
    [ProductName]   NVARCHAR (30) NOT NULL,
    [CategoryID]   VARCHAR (10)  NOT NULL,
    [Unit]          NVARCHAR (10) NOT NULL,
    [Price]         INT           NOT NULL,
    [Stock]         TINYINT       NOT NULL,
    [ProductStatus] BIT           NOT NULL,
    CONSTRAINT [PK_PRODUCT] PRIMARY KEY CLUSTERED ([ProductID] ASC)
);
 ALTER TABLE PRODUCT 
 ADD CONSTRAINT FK_PRODUCT_CATEGORY FOREIGN KEY (CategoryID) REFERENCES CATEGORY (CategoryID)

/*Create GOODS_ISSUE*/
CREATE TABLE [dbo].[GOODS_ISSUE] (
    [GoodsIssueID]    VARCHAR (15)  NOT NULL,
    [OrderID]        VARCHAR (15)  NOT NULL,
    [EmployeeID]     TINYINT       NOT NULL,
    [DateIssue]      DATETIME      NOT NULL,
    [ShippingUnitID] VARCHAR (5)  NOT NULL,
    [WarehouseName]  NVARCHAR (20) NOT NULL,
    CONSTRAINT [PK_GOODS_ISSUE] PRIMARY KEY CLUSTERED ([GoodsIssueID] ASC)
);
ALTER TABLE GOODS_ISSUE
   ADD CONSTRAINT FK_GOODS_ISSUE_SHIPPING_UNIT FOREIGN KEY (ShippingUnitID)
      REFERENCES SHIPPING_UNIT(ShippingUnitID)
ALTER TABLE GOODS_ISSUE
   ADD CONSTRAINT FK_GOODS_ISSUE_EMPLOYEE FOREIGN KEY (EmployeeID)
      REFERENCES EMPLOYEE(EmployeeID)
/*RUN AFTER CREATE TABLE ORDER*/
ALTER TABLE GOODS_ISSUE
   ADD CONSTRAINT FK_GOODS_ISSUE_ORDER FOREIGN KEY (OrderID)
      REFERENCES "ORDER"(OrderID)

/*Create GOODS_ISSUE_DOC_DETAIL*/
CREATE TABLE [dbo].[GOODS_ISSUE_DOC_DETAIL] (
    [GoodsIssueID]   VARCHAR (15)  NOT NULL,
    [ProductID]     VARCHAR (10)  NOT NULL,
    [Quantity]      TINYINT       NOT NULL,
    [Unit]          NVARCHAR (10) NOT NULL,
    [SubTotalPrice] INT           NOT NULL,
    CONSTRAINT [PK_GOODS_ISSUE_DOC_DETAIL] PRIMARY KEY CLUSTERED ([GoodsIssueID] ASC, [ProductID] ASC )
);

ALTER TABLE GOODS_ISSUE_DOC_DETAIL
   ADD CONSTRAINT FK_GOODS_ISSUE_DOC_DETAIL_PRODUCT FOREIGN KEY (ProductID)
      REFERENCES PRODUCT(ProductID)
ALTER TABLE GOODS_ISSUE_DOC_DETAIL
   ADD CONSTRAINT FK_GOODS_ISSUE_DOC_DETAIL_GOOD_ISSUE FOREIGN KEY (GoodsIssueID)
      REFERENCES GOODS_ISSUE(GoodsIssueID)

/*Create DELIVERY_RECEIPT*/
CREATE TABLE [dbo].[DELIVERY_RECEIPT] (
    [DeliveryReceiptID] VARCHAR (15) NOT NULL,
    [GoodsIssueID]       VARCHAR (15) NOT NULL,
    [COD]               INT          NOT NULL,
    [ShippingUnitID]    VARCHAR (5)  NOT NULL,
    [CreateDate]        DATETIME     NOT NULL,
    [DeliveryDate]      DATETIME     NULL,
    [Status]          BIT          NOT NULL,
    CONSTRAINT [PK_DELIVERY_RECEIPT] PRIMARY KEY CLUSTERED ([DeliveryReceiptID] ASC)
);
ALTER TABLE DELIVERY_RECEIPT
   ADD CONSTRAINT FK_DELIVERY_RECEIPT_GOODS_ISSUE FOREIGN KEY (GoodsIssueID)
      REFERENCES GOODS_ISSUE(GoodsIssueID)
ALTER TABLE DELIVERY_RECEIPT
   ADD CONSTRAINT FK_DELIVERY_RECEIPT_SHIPPING_UNIT FOREIGN KEY (ShippingUnitID)
      REFERENCES SHIPPING_UNIT(ShippingUnitID)

/*Create ORDER*/
CREATE TABLE [dbo].[ORDER] (
    [OrderID]           VARCHAR (15)   NOT NULL,
    [CustomerID]        INT            NOT NULL,
    [TotalQuantity]     TINYINT        NOT NULL,
    [TotalPrice]        INT            NOT NULL,
    [DiscountID]        VARCHAR (10)   NOT NULL,
    [CusAddressNumber]  NVARCHAR (50)  NOT NULL,
    [CusWard]           NVARCHAR (30)  NOT NULL,
    [CusDistrict]       NVARCHAR (20)  NOT NULL,
    [CusProvince]       NVARCHAR (50)  NOT NULL,
    [CreateDate]        DATETIME       NOT NULL,
    [OrderStatus]       CHAR (3)       NOT NULL,
    [DeliveryReceiptID] VARCHAR (15)   NOT NULL,
    [Note]              NVARCHAR (100) NULL,
    CONSTRAINT [PK_ORDER] PRIMARY KEY CLUSTERED ([OrderID] ASC)
);
ALTER TABLE "ORDER"
   ADD CONSTRAINT FK_ORDER_CUSTOMER FOREIGN KEY (CustomerID)
      REFERENCES CUSTOMER(CustomerID)
ALTER TABLE "ORDER"
   ADD CONSTRAINT FK_ORDER_DISCOUNT FOREIGN KEY (DiscountID)
      REFERENCES DISCOUNT(DiscountID)
ALTER TABLE "ORDER"
   ADD CONSTRAINT FK_ORDER_DELIVERY_RECEIPT FOREIGN KEY (DeliveryReceiptID)
      REFERENCES DELIVERY_RECEIPT(DeliveryReceiptID)

/*Create ORDER_DETAIL*/
CREATE TABLE [dbo].[ORDER_DETAIL] (
    [OrderID]         VARCHAR (15)  NOT NULL,
    [OrderlineNumber] TINYINT       NOT NULL,
    [ProductID]       VARCHAR (10)  NOT NULL,
    [Quantity]        TINYINT       NOT NULL,
    [Unit]            NVARCHAR (10) NOT NULL,
    [SubTotalPrice]   INT           NOT NULL,
    CONSTRAINT [PK_ORDER_DETAIL] PRIMARY KEY CLUSTERED ([OrderID] ASC,[ProductID] ASC)
);
ALTER TABLE ORDER_DETAIL
   ADD CONSTRAINT FK_ORDER_DETAIL_PRODUCT FOREIGN KEY (ProductID)
      REFERENCES PRODUCT(ProductID)
ALTER TABLE ORDER_DETAIL
   ADD CONSTRAINT FK_ORDER_DETAIL_ORDER FOREIGN KEY (OrderID)
      REFERENCES "ORDER"(OrderID)

/*Create INVOICE*/
CREATE TABLE [dbo].[INVOICE] (
    [InvoiceNumber] VARCHAR (15)  NOT NULL,
    [OrderID]       VARCHAR (15)  NOT NULL,
    [TotalCost]     INT           NOT NULL,
    [InvoiceDate]   DATETIME      NOT NULL,
    [PaymentMethod] BIT           NOT NULL,
    [PaymentStatus] NVARCHAR (15) NOT NULL,
    CONSTRAINT [PK_INVOICE] PRIMARY KEY CLUSTERED ([InvoiceNumber] ASC)
);
ALTER TABLE INVOICE
   ADD CONSTRAINT FK_INVOICE_ORDER FOREIGN KEY (OrderID)
      REFERENCES "ORDER"(OrderID)
      
/*Create GOODS_RETURN*/
CREATE TABLE [dbo].[GOODS_RETURN] (
    [GoodsReturnID] VARCHAR (15)    NOT NULL,
    [CustomerID]    INT          NOT NULL,
    [GoodsIssueID]  VARCHAR (15) NOT NULL,
    [EmployeeID]    TINYINT NOT NULL,
    [CreateDate]    DATETIME     NOT NULL,
    [ReturnStatus]  BIT          NOT NULL,
    [ExchangeType]  BIT          NOT NULL,
    CONSTRAINT [PK_ GOODS_RETURN] PRIMARY KEY CLUSTERED ([GoodsReturnID] ASC)
);
ALTER TABLE GOODS_RETURN
   ADD CONSTRAINT FK_GOODS_RETURN_CUSTOMER FOREIGN KEY (CustomerID)
      REFERENCES CUSTOMER(CustomerID)
ALTER TABLE GOODS_RETURN
   ADD CONSTRAINT FK_GOODS_GOODS_ISSUE FOREIGN KEY (GoodsIssueID)
      REFERENCES GOODS_ISSUE(GoodsIssueID)
ALTER TABLE GOODS_RETURN
   ADD CONSTRAINT FK_GOODS_RETURN_EMPLOYEES FOREIGN KEY (EmployeeID)
      REFERENCES EMPLOYEE(EmployeeID)

/*Create GOODS_EXCHANGE*/
CREATE TABLE [dbo].[GOODS_EXCHANGE] (
    [G_GoodsReturnID] VARCHAR (15)  NOT NULL,
    [GoodsExchangeID] VARCHAR (10)  NOT NULL,
    [Unit]            NVARCHAR (10) NOT NULL,
    [Quantity]        TINYINT       NOT NULL,
    CONSTRAINT [PK_GOODS_EXCHANGE] PRIMARY KEY CLUSTERED ([G_GoodsReturnID] ASC)
);
ALTER TABLE GOODS_EXCHANGE
    ADD CONSTRAINT FK_GOODS_EXCHANGE_GOODS_RETURN FOREIGN KEY (G_GoodsReturnID)
    REFERENCES GOODS_RETURN (GoodsReturnID)
ALTER TABLE GOODS_EXCHANGE
     ADD CONSTRAINT FK_PRODUCT_GOODS_RETURN FOREIGN KEY (GoodsExchangeID)
     REFERENCES PRODUCT(ProductID)

/*Create PAYMENT_RETURN*/
CREATE TABLE [dbo].[PAYMENT_RETURN] (
    [P_GoodsReturnID] VARCHAR (15)  NOT NULL,
    [ReturnAmount] INT  NOT NULL
    CONSTRAINT [PK_PAYMENT_STATUS] PRIMARY KEY CLUSTERED ([P_GoodsReturnID] ASC)
);
ALTER TABLE PAYMENT_RETURN
    ADD CONSTRAINT FK_PAYMENT_RETURN_GOODS_RETURN FOREIGN KEY (P_GoodsReturnID)
    REFERENCES GOODS_RETURN (GoodsReturnID)

/*Create GOODS_RETURN_DETAIL*/
CREATE TABLE [dbo].[GOODS_RETURN_DETAIL] (
    [GoodsReturnID] VARCHAR (15)   NOT NULL,
    [ProductID]     VARCHAR (10)   NOT NULL,
    [Quantity]      TINYINT        NOT NULL,
    [Unit]          NVARCHAR (10) NOT NULL,
    [SubTotalPrice] INT            NOT NULL,
    [Reason]        NVARCHAR (50)  NOT NULL,
    CONSTRAINT [PK_GOODS_RETURN_DETAILS] PRIMARY KEY CLUSTERED ([GoodsReturnID] ASC, [ProductID] ASC)
);
ALTER TABLE GOODS_RETURN_DETAIL
   ADD CONSTRAINT FK_GOODS_RETURN_DETAIL_GOODS_RETURN FOREIGN KEY (GoodsReturnID)
      REFERENCES GOODS_RETURN(GoodsReturnID)
ALTER TABLE GOODS_RETURN_DETAIL
   ADD CONSTRAINT FK_GOODS_RETURN_DETAIL_PRODUCT FOREIGN KEY (ProductID)
      REFERENCES PRODUCT(ProductID)

